<h3 class="text-center">Sign in</h3>
<div class="col-lg-6 col-lg-offset-3">
    <?php if(isset($this->flashmsgs)) { ?>
        <?php foreach($this->flashmsgs as $msg){
                foreach ($msg as $key=>$message) { ?>
                    <div class="alert alert-danger">
                        <h3 class="text-center"><i class="fa fa-close"></i> <?= $message ?></h3>
                    </div>
            <?php } } }?>
    <?= $this->form->renderForm(false) ?>
    <div class="form-group floating-label">
        <label for="" class="control-label">
            <?= $this->form->username->getLabel() ?>
        </label>
        <?= $this->form->username->renderViewHelper() ?>
    </div>

    <div class="form-group floating-label">
        <label for="" class="control-label">
            <?= $this->form->password->getLabel() ?>
        </label>
        <?= $this->form->password->renderViewHelper() ?>
    </div>
    <div class="form-group" style="overflow: hidden;">
        <button class="btn btn-info pull-right">
            <i class="fa fa-sign-in"></i> Connect
        </button>
    </div>
</div>


