<?= $this->doctype() ?>
<html>
<head>
    <?= $this->headTitle(" - ZendOne") ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Loading the styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl() . '/img/favicon.ico'))
        ->prependStylesheet($this->baseUrl() . '/css/font-awesome.min.css')
        //->prependStylesheet($this->basePath() . '/css/font-awesome.css')
        ->prependStylesheet($this->baseUrl() . '/css/bootstrap.min.css')
        //->prependStylesheet($this->basePath() . '/css/demo.css')
        ->prependStylesheet($this->baseUrl() . '/css/cropper.css')
        ->prependStylesheet($this->baseUrl() . '/css/material-kit.css') ?>

    <?php echo $this->headScript()
        ->appendFile($this->baseUrl() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->appendFile($this->baseUrl() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ->appendFile($this->baseUrl() . '/js/jquery.min.js')
        ->appendFile($this->baseUrl() . '/js/bootstrap.min.js')
        ->appendFile($this->baseUrl() . '/js/cropper.js')
        ->appendFile($this->baseUrl() . '/js/app.js')
        ->appendFile($this->baseUrl() . '/js/material.min.js')
        ->appendFile($this->baseUrl() . '/js/material-kit.js')
        //<!-- Scripts -->
    ; ?>
</head>
<body>
<nav class="navbar navbar-info">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="">MyZendApp</a>
        </div>

        <div class="collapse navbar-collapse" id="navigation-example">
            <ul class="nav navbar-nav">
                <li>
                    <a href=""><i class="fa fa-plus-square"></i> Add Post
                    </a>
                </li>
            </ul>
            <div class="col-sm-4 col-md-4">
            </div>

            <ul class="nav navbar-nav navbar-right pull-right">

            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="main main-raised" style="">
        <div class="container">
            <?= $this->layout()->content; ?>
        </div>
    </div>
</div>
</body>
</html>