<?php echo $this->doctype();
    $this->searchForm->setAction($this->url(['controller' => 'post', 'action' => 'search']));
?>
<html>
<head>
    <?= $this->headTitle("ZendOne")->setSeparator('-') ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Loading the styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl() . '/img/favicon.ico'))
        ->prependStylesheet($this->baseUrl() . '/css/font-awesome.min.css')
        //->prependStylesheet($this->basePath() . '/css/font-awesome.css')
        ->prependStylesheet($this->baseUrl() . '/css/bootstrap.min.css')
        //->prependStylesheet($this->basePath() . '/css/demo.css')
        ->prependStylesheet($this->baseUrl() . '/css/cropper.css')
        ->prependStylesheet($this->baseUrl() . '/css/material-kit.css') ?>

    <?php echo $this->headScript()
        ->appendFile($this->baseUrl() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->appendFile($this->baseUrl() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ->appendFile($this->baseUrl() . '/js/jquery.min.js')
        ->appendFile($this->baseUrl() . '/js/bootstrap.min.js')
        ->appendFile($this->baseUrl() . '/js/cropper.js')
        ->appendFile($this->baseUrl() . '/js/app.js')
        ->appendFile($this->baseUrl() . '/js/material.min.js')
        ->appendFile($this->baseUrl() . '/js/material-kit.js')
        //<!-- Scripts -->
    ; ?>
</head>
<body>
<nav class="navbar navbar-info">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url(['controller' => 'post', 'action' => 'index']) ?>">ZendOne</a>
        </div>

        <div class="collapse navbar-collapse" id="navigation-example">
            <ul class="nav navbar-nav">
                <li>
                    <a href="<?= $this->url(['controller' => 'post', 'action' => 'add']) ?>"><i class="fa fa-plus-square"></i> Add Post
                    </a>
                </li>
            </ul>
            <?= $this->render('/post/searchForm.phtml') ?>
            <?php if (Zend_Auth::getInstance()->hasIdentity()) { ?>
                <ul class="nav navbar-nav navbar-right pull-right">
                    <!-- The user is logged in -->

                    <li class="dropdown">
                        <a href="" class="dropdown-toggle profile" data-toggle="dropdown" aria-expanded="true">
                            <?php if ($this->profile->avatar) { ?>
                            <img height="30" width="30" src="<?= $this->baseurl('../data/uploads/profile/' . $this->profile->avatar); ?>" alt="user-img" class="img-circle">
                        <?php } else { ?>
                            <img height="30" width="30" src="<?= $this->baseurl('../public/img/profilepic.png'); ?>" alt="user-img" class="img-circle">
                            <i class="fa fa-caret-down" ></i> </a>
                        <?php } ?>

                        <ul class="dropdown-menu">
                            <li><a href="<?= $this->url(['controller' => 'profile', 'action' => 'display']) ?>"><i class="fa fa-user"></i> Profile</a></li>
                            <li><a href="<?= $this->url(['controller' => 'profile', 'action' => 'edit']); ?>"><i class="fa fa-cogs"></i> Settings</a></li>
                            <li class="divider"></li>
                        </ul>
                    </li>
                    <li><a href="<?= $this->url(['controller' => 'authentication', 'action' => 'logout']) ?>" style="margin-top: 8px !important;"><i class="fa fa-sign-out"></i> Logout</a></li>
                </ul>
            <?php } else { ?>
                <ul class="nav navbar-nav navbar-right pull-right">
                    <!-- The used is not logged in -->
                    <li>
                        <a href="<?= $this->url(['controller' => 'authentication', 'action' => 'login']) ?>"><i class="fa fa-sign-in"></i> LOGIN
                        </a>
                    </li>
                    <li>
                        <a href="<?= $this->url(['controller' => 'register', 'action' => 'register']) ?>" ><i class="fa fa-sign-out"></i> REGISTER
                        </a>
                    </li>
                </ul>
            <?php } ?>
        </div>
    </div>
</nav>
<br><br>
<div class="col-lg-9" >
    <div class="main main-raised" style="margin-top: 0px;">
        <div class="container">
            <div class="col-lg-9" >
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </div>
</div>

<div class="col-lg-3">
    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="text-center">Recommended</span>
        </div>
        <div class="panel-body">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, ad consequatur cum cumque deserunt dolorem eaque eligendi facere impedit incidunt nihil odit officia qui quia quisquam, ratione unde? Incidunt, quibusdam?</p>
        </div>
    </div>
</div>
<hr>
<div class="clearfix"></div>
<footer>
    <p class="text-center"> Copyright &copy; 2015 - <?php echo date('Y') ?> Fabour <?php echo $this->translate('All rights reserved.') ?></p>
</footer>

<?php echo $this->inlineScript() ?>
</body>
</html>