<?php
    //$this->profileForm->setAction($this->url(['controller' => 'profile', 'action' => 'avatar']));
    $this->profileForm->setAction($this->url());

    $this->headTitle('Settings');
    //Set the avatar form action
    /*
    $imageForm->setAttribute('action', $this->url('profile', array('action' => 'upload')));
    $imageForm->setAttribute('id', 'myForm');
    $imageForm->prepare();
    */
?>
<br><br>
<div class="col-lg-10 col-lg-offset-1">
    <?php if(isset($this->flashmsgs)) { ?>
    <?php foreach($this->flashmsgs as $msg){
        foreach ($msg as $key=>$message) { ?>
            <div class="alert alert-success">
                <h3 class="text-center"><i class="fa fa-check-circle"></i> <?= $message ?></h3>
            </div>
    <?php } } }?>
    <div class="card card-nav-tabs">
        <div class="header header-info">
            <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->
            <div class="nav-tabs-navigation">
                <div class="nav-tabs-wrapper nav-align-center">
                    <ul class="nav nav-pills" data-tabs="tabs">
                        <li class="active">
                            <a href="#profile" data-toggle="tab" aria-expanded="false">
                                <i class="fa fa-user"></i>
                                Informations
                                <div class="ripple-container"></div></a>
                        </li>
                        <li class="">
                            <a href="#messages" data-toggle="tab" aria-expanded="true">
                                <i class="fa fa-camera-retro"></i>
                                Avatar
                                <div class="ripple-container"></div></a>
                        </li>
                        <li class="">
                            <a href="#posts" data-toggle="tab" aria-expanded="false">
                                <i class="fa fa-file-archive-o"></i>
                                Posts
                                <div class="ripple-container"></div></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="content" style="overflow: hidden">
            <div class="tab-content">
                <div class="tab-pane active" id="profile">
                    <div class="col-lg-8 col-lg-offset-2">

                        <?php echo $this->profileForm->renderForm(false); ?>
                        <?= $this->profileForm->id->renderViewHelper()  ?>
                        <div class="form-group label-floating">
                            <label class="control-label">
                                <?= $this->profileForm->username->getLabel() ?>
                            </label>
                            <?= $this->profileForm->username->renderViewHelper() ?>
                        </div>

                        <div class="form-group label-floating">
                            <label class="control-label">
                                <?= $this->profileForm->firstname->getLabel() ?>
                            </label>
                            <?= $this->profileForm->firstname->renderViewHelper() ?>
                        </div>

                        <div class="form-group label-floating">
                            <label class="control-label">
                                <?= $this->profileForm->lastname->getLabel() ?>
                            </label>
                            <?= $this->profileForm->lastname->renderViewHelper() ?>
                        </div>

                        <div class="form-group label-floating">
                            <label class="control-label">
                                <?= $this->profileForm->mobile->getLabel() ?>
                            </label>
                            <?= $this->profileForm->mobile->renderViewHelper() ?>
                        </div>

                        <div class="form-group label-floating">
                            <label class="control-label">
                                <?= $this->profileForm->interests->getLabel() ?>
                            </label>
                            <?= $this->profileForm->interests->renderViewHelper() ?>
                        </div>

                        <div class="form-group label-floating">
                            <label class="control-label">
                                <?= $this->profileForm->occupation->getLabel() ?>
                            </label>
                            <?= $this->profileForm->occupation->renderViewHelper() ?>
                        </div>

                        <div class="form-group label-floating">
                            <label class="control-label">
                                <?= $this->profileForm->about->getLabel() ?>
                            </label>
                            <?= $this->profileForm->about->renderViewHelper() ?>
                        </div>

                        <button type="submit" class="btn btn-info btn-round btn-block"><i class="fa fa-save"></i> Save Changes</button>

                    </div>

                </div>
                <div class="tab-pane" id="messages">
                    <div class="col-lg-6 col-lg-offset-3">
                        <?php if ($this->profileSettings->avatar) { ?>
                            <img class="img-responsive preview" src="<?= $this->baseurl('../data/uploads/profile/' . $this->profileSettings->avatar) ?>" id="image-file">
                        <?php } else { ?>
                            <img class="img-responsive preview" src="<?= $this->baseurl('img/profilePic.png') ?>" id="image-file">
                        <?php } ?>
                        <form action="<?= $this->url(['controller' => 'post', 'action' => 'upload']) ?>"></form>
                        <?= $this->avatarForm ?>
                    </div>
                </div>
                <div class="tab-pane" id="posts">
                    <?php if (!count($this->posts)) { ?>
                        <h3 class="text-center text-info">Opps, this user has not posted anything yet!</h3>
                    <?php } else { ?>
                        <?php foreach ($this->posts as $post) { ?>
                            <div class="col-lg-4">
                                <div class="panel panel-info">
                                    <div class="panel-heading" style="color: white">
                                        <strong><?= $post->title ?></strong>
                                    </div>
                                    <div class="panel-body">
                                        <?php if ($post->cover) { ?>
                                            <img class="img-responsive" width="300px" height="180px" src="<?= $this->baseurl('../data/uploads/covers/' . $post->cover) ?>" alt="">
                                        <?php } else { ?>
                                            <img class="img-responsive" width="300px" height="180px" src="<?= $this->baseurl('/img/no-cover.png') ?>" alt="">
                                        <?php } ?>
                                    </div>
                                    <div class="panel-footer">
                                        <div class="btn-group">
                                            <a href="<?= $this->url(array('controller' => 'post', 'action' => 'edit', 'id' => $post->id )) ?>" class="btn btn-round btn-info"><i class="fa fa-edit"></i> </a>
                                            <a href="<?= $this->url(array('controller' => 'post', 'action' => 'delete', 'id' => $post->id )) ?>" class="btn btn-round btn-danger"><i class="fa fa-trash"></i> </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php }} ?>
                </div>
            </div>
        </div>
    </div>
</div>