<?php
$this->headTitle($post->title);
?>

<div class="section section-landing">
    <div class="col-lg-10 col-lg-offset-1">
        <div class="row">
            <p>
                <strong><span class="pull-left text-primary"><?= $post->title ?> - </span></strong> <em> <?= $post->getCategory()->name ?></em>
                <strong><span class="pull-right text-primary">Price : <?= $post->price ?></span></strong>
            </p>
        </div>
        <hr>
        <div class="avatar">
            <?php if ($post->cover) {  ?>
                <img class="img-responsive img-rounded img-raised center-block" src="<?= $this->basepath('../data/uploads/covers/' . $post->cover) ?>">
            <?php } else { ?>
                <img class="img-responsive img-rounded img-raised center-block" src="<?= $this->basepath('../public/img/no-cover.png') ?>">
            <?php } ?>
        </div>
        <!--<h2 class="text-center">"Username Here"</h2>-->
        <br>
        <h6 class="text-center text-uppercase">Description</h6>
        <p class="text-center description"><?= $post->description ?></p>
        <hr>
        <h1 class="text-center text-primary">GALLERY GON' BE HERE</h1>

        <hr>
        <div class="section section-landing">
            <h2>CONTACT:</h2>
            <p>
                <span class="pull-left"><strong><em>Phone:</em></strong><?= $post->phone ?></span>
                <span class="pull-right"><strong><em>Email:</em></strong><?= $post->email ?></span>
            </p>
        </div>
    </div>
</div>


