<?php
$this->headTitle("Index page man");
?>
<br><br>
<div class="col-lg-10 col-lg-offset-1">
	<?php foreach ($this->paginator as $post) : ?>
		
		<div class="card" style="width: 300px; overflow: hidden; margin-left: 10px;">
			<?php
			if ($post->cover) {
				?>
				<img height="180px" class="card-img-top" src="<?= $this->baseurl('../data/uploads/covers/' . $post->cover) ?> " alt="<?= $post->title ?>">
				<?php

			} else {
				?>
				<img height="180px" class="card-img-top" src="<?= $this->baseurl('/img/no-cover.png') ?>" alt="Card image cap">
				<?php
			}
			?>
			<div class="card-block" style="padding: 10px;">
				<h4 class="card-title">
					<a href="<?= $this->url(array('action' => 'display', 'id' => $post->id)) ?>">
						<?= $post->title ?>
					</a><br>
					<span style="font-size: 8pt"><em></em></span>
				</h4>
				<p class="card-text"><?= $post->description ?>.</p>
				<a href="<?= $this->url(array('action' => 'display', 'id' => $post->id)) ?>" class="btn btn-primary"><i class="fa fa-bars"></i> More</a>
			</div>
		</div>
	<?php endforeach; ?>

	<?php
	
	// add at the end of the file after the table
	echo $this->paginationControl(
	// the paginator object
		$this->paginator,
		// the scrolling style
		'sliding',
		// the partial to use to render the control
		'partial/paginator.phtml',
		// the route to link to when a user clicks a control link
		array(
			'route' => 'post'
		)
	);

	?>

</div>
