<?php
$this->headTitle("Search result for "  . $this->title);

if (empty($this->posts)) {
?>

<div class="alert alert-info">
    <div class="container-fluid">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"><i class="fa fa-windows"></i></span>
        </button>
        <b class="fa fa-info-circle"></b> Opps, it looks like the title you entered doesn't match anything in our system
    </div>
</div>
<?php
}
?>
<br>
<h3 class="text-info">Search result for: <?= $this->title ?>  <?= count($this->posts) ?></h3>
<?php foreach ($this->posts as $post) : ?>
    <div class="card" style="width: 300px; height overflow: hidden; margin-left: 10px;">
        <?php
        if ($post->cover) {
            ?>
            <img height="180" class="card-img-top" src="<?= $this->baseurl('../data/uploads/covers/' . $post->cover) ?> " alt="<?= $post->title ?>">
            <?php

        } else {
            ?>
            <img height="180" class="card-img-top" src="<?= $this->baseurl('/img/no-cover.png') ?>" alt="Card image cap">
            <?php
        }

        ?>
        <div class="card-block" style="padding: 10px;">
            <h4 class="card-title">
                <a href="<?= $this->url(array('controller' => 'post', 'action' => 'display', 'id' => $post->id)) ?>">
                    <?= $post->title ?>
                </a><br></h4>
            <p class="card-text"><?= $post->description ?>.</p>
            <a href="<?= $this->url(array('controller' => 'post', 'action' => 'display', 'id' => $post->id)) ?>" class="btn btn-primary"><i class="fa fa-bars"></i> More</a>
        </div>
    </div>
<?php endforeach; ?>

<?php
/*
// add at the end of the file after the table
echo $this->paginationControl(
// the paginator object
    $this->paginator,
    // the scrolling style
    'sliding',
    // the partial to use to render the control
    'partial/paginator.phtml',
    // the route to link to when a user clicks a control link
    array(
        'route' => 'post'
    )
);
*/
?>

<br><br>
