<div class="col-sm-4 col-md-4">
    <?php if (Zend_Auth::getInstance()->hasIdentity()) {?>
        <form enctype="application/x-www-form-urlencoded" style="margin-top: 8px !important;" class="navbar-form" action="/zendone/public/post/search" method="post">
            <div class="input-group">
                <?php if ($this->searchForm->search) {?>
                    <?php echo $this->searchForm->search->renderViewHelper(); ?>

                    <div class="input-group-btn">
                        <button class="btn btn-info btn-just-icon" type="submit"><i class="fa fa-search-plus"></i></button>
                    </div>
                <?php } ?>
            </div>
    <?php } ?>

        </form>
</div>